FROM trivadis/apache-spark-scala-template:2.4.7-hadoop2.8

MAINTAINER Guido Schmutz <guido.schmutz@gmail.com>

ENV SPARK_APPLICATION_MAIN_CLASS com.trivadis.sample.spark.SimpleApp
ENV SPARK_MASTER_NAME spark-master
ENV SPARK_MASTER_PORT 7077