FROM trivadis/apache-spark-template-java:2.4.7-hadoop2.8

MAINTAINER XXX YYY <xxx.yyy@gmail.com>

ENV SPARK_APPLICATION_JAR_NAME spark-java-sample-1.0-SNAPSHOT.jar
ENV SPARK_APPLICATION_MAIN_CLASS com.trivadis.sample.spark.SimpleApp
ENV SPARK_MASTER_NAME spark-master
ENV SPARK_MASTER_PORT 7077
