FROM trivadis/apache-spark-python-template:2.4.7-hadoop2.8

MAINTAINER You <you@example.org>

ENV SPARK_APPLICATION_PYTHON_LOCATION /app/simple-app.py
# ENV SPARK_APPLICATION_ARGS "foo bar baz"
ENV SPARK_MASTER_NAME spark-master
ENV SPARK_MASTER_PORT 7077
